### PR TITLE
(chore) make the android unit tests green again

### PR DESCRIPTION
**Pull request by maiatoday**
## Summary

The android unit tests did not compile. Now they compile and pass again. I added a mock for the repository.

## How It Was Tested

I ran the unit tests.

## Screenshot/Gif

<details>

<summary>Before</summary>

Screenshot 2024-08-31 at 21 19 17

</details>

<details>

<summary>After</summary>

Screenshot 2024-08-31 at 21 16 52

</details>

### CODE REVIEW

**Review by alisen — APPROVED** [review]
Good catch!

**Comment by alisen** [comment]
> @alisen what is the etiquette for PRs on this repo? Am I expected to merge these myself if they are approved?

@maiatoday That’s a great question! At Droidcon, we usually handled the merging ourselves, but currently, I can confirm that no official rule has been established for this. That’s why I left the merging decision up to you.

**Comment by maiatoday** [comment]
> > @alisen what is the etiquette for PRs on this repo? Am I expected to merge these myself if they are approved?
> 
> @maiatoday That’s a great question! At Droidcon, we usually handled the merging ourselves, but currently, I can confirm that no official rule has been established for this. That’s why I left the merging decision up to you.

OK I'll merge these two, that way atleast the dependabot ones will go in

**Comment by alisen** [comment]
> > > @alisen what is the etiquette for PRs on this repo? Am I expected to merge these myself if they are approved?
> > 
> > 
> > @maiatoday That’s a great question! At Droidcon, we usually handled the merging ourselves, but currently, I can confirm that no official rule has been established for this. That’s why I left the merging decision up to you.
> 
> ~OK I'll merge these two, that way atleast the dependabot ones will go in~ I don't think I can merge them

Thanks for trying to merge the PRs. It seems like our settings might be causing an issue. I'll merge them. We'll also discuss what we can do about this going forward.

**Pull request merged**
