### PR TITLE
Implemented feature to store a page on a selected button of the badge

### PR DESCRIPTION
**Pull request by Zoro38**

### CODE REVIEW

**Review by Urizel — APPROVED** [review]

**Review by Urizel — APPROVED** [review]

**Comment by milosmns** [comment]
@Zoro38 oh no, merge conflicts 😱

**Comment by Zoro38** [comment]
> @Zoro38 oh no, merge conflicts 😱

Fixed 😄

**Comment by milosmns** [comment]
@Zoro38 There are some conflicts; it's probably best to join us at ZeBooth™ and resolve them in-place, then merge them together with us! See you when you come to pick up your badge 👋

**Comment by mariobodemann** [comment]
Thank you for your contribution. Sadly we will be going in a different direction with the storing of pages and sending them to the badge. 

Thanks again, ZeTeam.

**Pull request closed without merging**
