### PR TITLE
replace toast with snackbar

### PR DESCRIPTION
**Pull request by forntoh**
This implementation centralises the use of the snackbar and reduces the boilerplate to show a toast
Also removes the need to pass down activity to composable screens

### CODE REVIEW

**Comment by louis993546** [comment]
Please resolve conflict

**Comment by milosmns** [comment]
@forntoh oh no, merge conflicts 😱

**Comment by forntoh** [comment]
> @forntoh oh no, merge conflicts 😱

Resolved

**Comment by forntoh** [comment]
Can't really count how many times I have fixed merge conflicts. 😪

😅 @milosmns

**Comment by milosmns** [comment]
@forntoh come to our booth and pressure someone into merging your PR 😄
More conflicts, wooohooo!

**Pull request merged**
